server:
  port: 8080

server.servlet.contextPath: /ecommerce-api/v1
logging.config: config/log4j2.yml
management:
  endpoints:
    web:
      exposure:
        include: "*"

#spring.servlet.multipart.enabled: false
#spring.servlet.multipart.resolve-lazily: false

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    database: MYSQL
    show-sql: true
    format_sql: true
    generate-ddl: false
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: hungiang
  database:
    driverClasName: com.mysql.jdbc.Driver

http:
  multipart:
    maxFileSize: 20MB
    maxRequestSize: 20MB

logging.level.org.hibernate.SQL: debug
#logging.level.org.hibernate.type.descriptor.sql: trace
spring.jpa.properties.hibernate.jdbc.batch_size: 10
spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers: true
spring.datasource.testOnBorrow: true
spring.datasource.validationQuery: SELECT 1
spring.jackson.serialization.write_dates_as_timestamps: false
#spring.jpa.properties.javax.persistence.schema-generation.create-source: metadata
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action: create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target: create.sql
